[default]
duration = "10m"
sorting = "random"
mode = "center"

# Widescreen 3440x1440
[DP-3]
path = "/home/ibrahim/.config/backgrounds/Alpstein.png"

# 1920x1200
[DP-2]
path = "/home/ibrahim/.config/backgrounds/Alpstein.png"
